# coding: utf-8

LAST_VOTE_KEY = "last_vote_key"
LAST_VOTE_TERM = "lastVoteTerm"
LAST_VOTE_CANDIDATE = "lastVoteCandidate"
CURRENT_TERM = "currentTerm"
BASE_PATH = "/var/lib/raft"

# FSM OP
OP_FSM_APPLY_LOG = 0
OP_FSM_TAKE_SNAPSHOT = 1
OP_FSM_RESTORE_SNAPSHOT = 2

# SNAPSHOT OP
OP_SNAPSHOT_USER = 0
OP_SNAPSHOT_TIMEOUT = 1
OP_SNAPSHOT_LIST = 2
OP_SNAPSHOT_OPEN = 3

RAFT_LEADER = 0
RAFT_CANDIDATE = 1
RAFT_FOLLOWER = 2

# RPC OP
REQUEST_VOTE = 1
REQUEST_VOTE_RESP = 2
APPEND_ENTRIES = 3
APPEND_ENTRIES_RESP = 4
